[install/debian] postinst: Teile neu geschrieben fuer groessere Fehlertoleranz und Kompatibilitaet mit aktullem debian, manuelle Installation von getnonfreefonts ermoeglicht

diff --git a/install/debian/postinst b/install/debian/postinst
--- a/install/debian/postinst
+++ b/install/debian/postinst
@@ -20,75 +20,102 @@ set -e
 case "$1" in
     configure)
 
-    if [ -x /usr/bin/mktexlsr ] ; then
+    if [ -x /usr/bin/mktexlsr ]; then
       /usr/bin/mktexlsr
-    fi
-    # Debugging output
-    pdftexmap=`kpsewhich pdftex.map`
-    echo "Found map file: $pdftexmap";
-    # Select if to use local version
-    varlibmap=`kpsewhich pdftex.map | grep /var/lib`
-    if [ -z "$varlibmap" ]; then
-      # Touch 10local.cfg to prevent errors of buggy updmap
-      mkdir -p ~/.texmf-config/updmap.d
-      touch ~/.texmf-config/updmap.d/10local.cfg
-
-      # Check for already available Mapfiles
-      npsans=`/usr/bin/updmap --listmaps 2>&1 | grep NexusProSerif | grep -v ! || true`
-      npserif=`/usr/bin/updmap --listmaps 2>&1 | grep NexusProSerif | grep -v ! || true`
-      
-      echo "You seem to use a local font map. Using local variants, too"
-      echo -n "Running getnonfreefonts to install arial-urw..."
-      /usr/bin/getnonfreefonts --verbose arial-urw > /dev/null 2>&1
-      if [ $? ] ; then echo '[OK]' ; else echo '[FAILED]'; fi
-      if [ -z "$npsans" ]; then
-        echo -n "Adding local map file for NexusProSans..."
-        /usr/bin/updmap --nomkmap --nohash --enable Map=NexusProSans.map > /dev/null 2>&1
-        if [ $? ] ; then echo '[OK]' ; else echo '[FAILED]'; fi
-      else
-        echo "NexusProSans already enabled, skipping..."
-      fi
-      if [ -z "$npserif" ]; then
-        echo -n "Adding local map file for NexusProSerif..."
-        /usr/bin/updmap --nomkmap --nohash --enable Map=NexusProSerif.map > /dev/null 2>&1
-        if [ $? ] ; then echo '[OK]' ; else echo '[FAILED]'; fi
-      else
-        echo "NexusProSerif already enabled, skipping..."
-      fi
-      echo -n "running updmap..."
-      /usr/bin/updmap > /dev/null 2>&1
-      if [ $? ] ; then echo '[OK]' ; else echo '[FAILED]'; fi
     else
-      # Touch 10local.cfg to prevent errors of buggy updmap
-      touch /etc/texmf/updmap.d/10local.cfg
-      
-      # Check for already available Mapfiles
-      npsans=`/usr/bin/updmap-sys --listmaps 2>&1 | grep NexusProSerif | grep -v ! || true`
-      npserif=`/usr/bin/updmap-sys --listmaps 2>&1 | grep NexusProSerif | grep -v ! || true`
+      echo "Error: /usr/bin/mktexlsr not found!"
+      exit 1
+    fi
+    if [ -x /usr/bin/kpsewhich ]; then
+      pdftexmap=`kpsewhich pdftex.map`
+      echo "Found map file: $pdftexmap"; # Debugging output
+    else
+      echo "Error: /usr/bin/kpsewhich not found!"
+      exit 1
+    fi
+    if [ ! -x /usr/bin/updmap-sys ]; then
+      echo "Error: /usr/bin/updmap-sys not found!"
+      exit 1
+    fi
+    
+    varlibmap=`echo $pdftexmap | grep /var/lib`
+    if [ -z "$varlibmap" ]; then
 
-      echo "Using sys variants"
+      echo "You seem to use a local font map ($pdftexmap)."
+      echo "It is recommended to use a global font map for this installation"
+      echo "Do you want to delete local font map? [y/n]"
+      read yesno
+      if [ $yesno == "y" ]; then
+        echo -n "Deleting $varlibmap..."
+        rm $varlibmap
+        echo "[DONE]"
+      else
+        echo "You may need to run updmap manually after install!"
+      fi
+    fi
+
+    # Touch 10local.cfg to prevent errors of buggy updmap
+    # TODO: This step might be skipped in texlive 201x
+    mkdir -p /etc/texmf/updmap.d
+    touch /etc/texmf/updmap.d/10local.cfg
+      
+    # Check for getnonfreefonts and install if needed
+    # Is either located at /usr/bin/getnonfreefonts-sys (as symlink)
+    # or at /usr/local/bin/getnonfreefonts
+    if ([ ! -x /usr/bin/getnonfreefonts-sys ] && [ ! -x /usr/local/bin/getnonfreefonts ]); then
+      # TODO: get getnonfreefonts
+      echo "getnonfreefonts was not found on your system."
+      echo "Do you want automatically download and install it? [y/n]"
+      read yesno
+      if [ $yesno = "y" ]; then
+        wget -P /tmp http://tug.org/fonts/getnonfreefonts/install-getnonfreefonts
+        texlua /tmp/install-getnonfreefonts
+        rm /tmp/install-getnonfreefonts
+#        /usr/bin/getnonfreefonts-sys --verbose arial-urw > /dev/null 2>&1
+      else
+        echo "Warning: Arial will not be installed!"
+        echo "You may need to install arial later manually"
+      fi
+    fi
+
+    # Fix broken symlinks if neccessary
+    if ([ ! -x /usr/bin/getnonfreefonts-sys ] && [ -x /usr/local/bin/getnonfreefonts ]); then
+      rm -f /usr/bin/getnonfreefonts-sys
+      ln -s /usr/local/bin/getnonfreefonts /usr/bin/getnonfreefonts-sys 
+    fi
+
+    if [ -x /usr/bin/getnonfreefonts-sys ]; then
       echo -n "Running getnonfreefonts-sys to install arial-urw..."
       /usr/bin/getnonfreefonts-sys --verbose arial-urw > /dev/null 2>&1
       if [ $? ] ; then echo '[OK]' ; else echo '[FAILED]'; fi
-      if [ -z "$npsans" ]; then
-        echo -n "Adding map file for NexusProSans..."
-        /usr/bin/updmap-sys --nomkmap --nohash --enable Map=NexusProSans.map > /dev/null 2>&1
-        if [ $? ] ; then echo '[OK]' ; else echo '[FAILED]'; fi
-      else
-        echo "NexusProSans already enabled, skipping..."
-      fi
-      if [ -z "$npserif" ]; then
-        echo -n "Adding map file for NexusProSerif..."
-        /usr/bin/updmap-sys --nomkmap --nohash --enable Map=NexusProSerif.map > /dev/null 2>&1
-        if [ $? ] ; then echo '[OK]' ; else echo '[FAILED]'; fi
-      else
-        echo "NexusProSerif already enabled, skipping..."
-      fi
-      echo -n "running updmap-sys..."
-      /usr/bin/updmap-sys > /dev/null 2>&1
-      if [ $? ] ; then echo '[OK]' ; else echo '[FAILED]'; fi
     fi
-    ;;
+
+    # Check for already available Mapfiles
+    # (Some updmap versions fail trying to enable an active map)
+    npsans=`/usr/bin/updmap-sys --listmaps 2>&1 | grep NexusProSerif | grep -v ! | grep -v disabled || true`
+    npserif=`/usr/bin/updmap-sys --listmaps 2>&1 | grep NexusProSerif | grep -v ! | grep -v disabled || true`
+
+    # Enable Nexus maps
+    if [ -z "$npsans" ]; then
+      echo -n "Adding map file for NexusProSans..."
+      /usr/bin/updmap-sys --nomkmap --nohash --enable Map=NexusProSans.map > /dev/null 2>&1
+      if [ $? ] ; then echo '[OK]' ; else echo '[FAILED]'; fi
+    else
+      echo "NexusProSans already enabled, skipping..."
+    fi
+    if [ -z "$npserif" ]; then
+      echo -n "Adding map file for NexusProSerif..."
+      /usr/bin/updmap-sys --nomkmap --nohash --enable Map=NexusProSerif.map > /dev/null 2>&1
+      if [ $? ] ; then echo '[OK]' ; else echo '[FAILED]'; fi
+    else
+      echo "NexusProSerif already enabled, skipping..."
+    fi
+
+    # Run updmap to update font db
+    echo -n "running updmap-sys..."
+    /usr/bin/updmap-sys > /dev/null 2>&1
+    if [ $? ] ; then echo '[OK]' ; else echo '[FAILED]'; fi
+  ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
 
