[install/debian] posints: Check fuer bereits aktivierte Maps, um Probleme mit updmap zu verhindern

diff --git a/install/debian/postinst b/install/debian/postinst
--- a/install/debian/postinst
+++ b/install/debian/postinst
@@ -33,33 +33,57 @@ case "$1" in
       mkdir -p ~/.texmf-config/updmap.d
       touch ~/.texmf-config/updmap.d/10local.cfg
 
+      # Check for already available Mapfiles
+      npsans=`/usr/bin/updmap --listmaps 2>&1 | grep NexusProSerif | grep -v ! || true`
+      npserif=`/usr/bin/updmap --listmaps 2>&1 | grep NexusProSerif | grep -v ! || true`
+      
       echo "You seem to use a local font map. Using local variants, too"
       echo -n "Running getnonfreefonts to install arial-urw..."
       /usr/bin/getnonfreefonts --verbose arial-urw > /dev/null 2>&1
       if [ $? ] ; then echo '[OK]' ; else echo '[FAILED]'; fi
-      echo -n "Adding local map file for NexusProSans..."
-      /usr/bin/updmap --nomkmap --nohash --enable Map=NexusProSans.map > /dev/null 2>&1
-      if [ $? ] ; then echo '[OK]' ; else echo '[FAILED]'; fi
-      echo -n "Adding local map file for NexusProSerif..."
-      /usr/bin/updmap --nomkmap --nohash --enable Map=NexusProSerif.map > /dev/null 2>&1
-      if [ $? ] ; then echo '[OK]' ; else echo '[FAILED]'; fi
+      if [ -z "$npsans" ]; then
+        echo -n "Adding local map file for NexusProSans..."
+        /usr/bin/updmap --nomkmap --nohash --enable Map=NexusProSans.map > /dev/null 2>&1
+        if [ $? ] ; then echo '[OK]' ; else echo '[FAILED]'; fi
+      else
+        echo "NexusProSans already enabled, skipping..."
+      fi
+      if [ -z "$npserif" ]; then
+        echo -n "Adding local map file for NexusProSerif..."
+        /usr/bin/updmap --nomkmap --nohash --enable Map=NexusProSerif.map > /dev/null 2>&1
+        if [ $? ] ; then echo '[OK]' ; else echo '[FAILED]'; fi
+      else
+        echo "NexusProSerif already enabled, skipping..."
+      fi
       echo -n "running updmap..."
       /usr/bin/updmap > /dev/null 2>&1
       if [ $? ] ; then echo '[OK]' ; else echo '[FAILED]'; fi
     else
       # Touch 10local.cfg to prevent errors of buggy updmap
       touch /etc/texmf/updmap.d/10local.cfg
+      
+      # Check for already available Mapfiles
+      npsans=`/usr/bin/updmap-sys --listmaps 2>&1 | grep NexusProSerif | grep -v ! || true`
+      npserif=`/usr/bin/updmap-sys --listmaps 2>&1 | grep NexusProSerif | grep -v ! || true`
 
       echo "Using sys variants"
       echo -n "Running getnonfreefonts-sys to install arial-urw..."
       /usr/bin/getnonfreefonts-sys --verbose arial-urw > /dev/null 2>&1
       if [ $? ] ; then echo '[OK]' ; else echo '[FAILED]'; fi
-      echo -n "Adding map file for NexusProSans..."
-      /usr/bin/updmap-sys --nomkmap --nohash --enable Map=NexusProSans.map > /dev/null 2>&1
-      if [ $? ] ; then echo '[OK]' ; else echo '[FAILED]'; fi
-      echo -n "Adding map file for NexusProSerif..."
-      /usr/bin/updmap-sys --nomkmap --nohash --enable Map=NexusProSerif.map > /dev/null 2>&1
-      if [ $? ] ; then echo '[OK]' ; else echo '[FAILED]'; fi
+      if [ -z "$npsans" ]; then
+        echo -n "Adding map file for NexusProSans..."
+        /usr/bin/updmap-sys --nomkmap --nohash --enable Map=NexusProSans.map > /dev/null 2>&1
+        if [ $? ] ; then echo '[OK]' ; else echo '[FAILED]'; fi
+      else
+        echo "NexusProSans already enabled, skipping..."
+      fi
+      if [ -z "$npserif" ]; then
+        echo -n "Adding map file for NexusProSerif..."
+        /usr/bin/updmap-sys --nomkmap --nohash --enable Map=NexusProSerif.map > /dev/null 2>&1
+        if [ $? ] ; then echo '[OK]' ; else echo '[FAILED]'; fi
+      else
+        echo "NexusProSerif already enabled, skipping..."
+      fi
       echo -n "running updmap-sys..."
       /usr/bin/updmap-sys > /dev/null 2>&1
       if [ $? ] ; then echo '[OK]' ; else echo '[FAILED]'; fi
