[install/debian] Inhalt von prerm in postrm verschoben, Weiche fuer lokale maps hinzugefuegt, aufgeraumt, cases korrigiert

diff --git a/install/debian/postrm b/install/debian/postrm
--- a/install/debian/postrm
+++ b/install/debian/postrm
@@ -19,24 +19,45 @@ set -e
 
 
 case "$1" in
-       purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
-    if [ -x /usr/bin/mktexlsr ] ; then
-    /usr/bin/mktexlsr
-    fi
-    echo "running updmap-sys"
-    /usr/bin/updmap-sys --quiet
+    purge|remove|abort-install|abort-upgrade|disappear)
+        if [ -x /usr/bin/mktexlsr ] ; then
+            /usr/bin/mktexlsr
+        fi
+        if [ -x /usr/bin/kpsewhich ] ; then
+            # Debugging output
+            pdftexmap=`kpsewhich pdftex.map`
+            echo "Found map file: $pdftexmap";
+            # Select if to use local version
+            varlibmap=`kpsewhich pdftex.map | grep /var/lib`
+        else
+            echo "kpsewhich not found. Aborting..."
+            exit 1
+        fi
+        if [ -z "$varlibmap" ]; then
+            echo "Removing map file for NexusProSans"
+            /usr/bin/updmap-sys --quiet --nomkmap --nohash --disable NexusProSans.map
+            echo "Removing map file for NexusProSerif"
+            /usr/bin/updmap-sys --quiet --nomkmap --nohash --disable NexusProSerif.map
+            echo "running updmap-sys"
+            /usr/bin/updmap-sys --quiet
+        else
+            echo "Removing map file for NexusProSans"
+            /usr/bin/updmap --quiet --nomkmap --nohash --disable NexusProSans.map
+            echo "Removing map file for NexusProSerif"
+            /usr/bin/updmap --quiet --nomkmap --nohash --disable NexusProSerif.map
+            echo "running updmap"
+            /usr/bin/updmap --quiet
+        fi
 
-        ;;
-
+    ;;
+    upgrade|failed-upgrade)
+        # nothing to to...
+    ;;
     *)
         echo "postrm called with unknown argument \`$1'" >&2
         exit 1
 
 esac
-
-# dh_installdeb will replace this with shell code automatically
-# generated by other debhelper scripts.
-
 
 
 exit 0
